# Generated by Django 4.2.5 on 2023-10-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_address_customuser_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='weight',
        ),
    ]
