# Generated by Django 4.2.5 on 2023-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customuser_address_remove_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile1',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
