# Generated by Django 4.2.5 on 2023-10-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile1_age_userprofile1_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile1',
            name='address',
        ),
    ]
