# Generated by Django 4.2.5 on 2023-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
