# Generated by Django 4.2.5 on 2023-11-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userrating_delete_trainerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
