# Generated by Django 4.2.5 on 2023-11-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_userrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='govt_id',
            field=models.FileField(blank=True, null=True, upload_to='govt_ids/'),
        ),
    ]
