# Generated by Django 4.2.5 on 2023-11-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='password',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
