# Generated by Django 4.2.5 on 2023-11-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_phone_trainer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificate/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='govt_id',
            field=models.FileField(blank=True, null=True, upload_to='govt_id/'),
        ),
    ]
