# Generated by Django 4.2.5 on 2023-11-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_trainer_certificate_alter_trainer_govt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='govt_id',
            field=models.FileField(blank=True, null=True, upload_to='govt_ids/'),
        ),
    ]
