# Generated by Django 4.2.5 on 2023-11-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_trainer_certificate_alter_trainer_govt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='time_slots',
            field=models.ManyToManyField(to='app.timeslot'),
        ),
    ]
