# Generated by Django 4.2.5 on 2023-11-15 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_trainer_time_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trainer'),
        ),
    ]
