# Generated by Django 4.2.5 on 2023-11-19 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_timeslot_trainer_timeslot_trainers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='trainers',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trainer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='time_slots',
            field=models.ManyToManyField(related_name='trainers', to='app.timeslot'),
        ),
    ]
