# Generated by Django 4.2.5 on 2023-11-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_timeslot_trainers_timeslot_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='trainer',
        ),
    ]
