# Generated by Django 4.2.5 on 2023-11-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_timeslot_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialization'),
        ),
    ]
