# Generated by Django 4.2.5 on 2023-11-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_trainer_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
