# Generated by Django 4.2.5 on 2023-11-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_userrating_trainer_delete_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('govt_id', models.FileField(blank=True, null=True, upload_to='govt_ids/')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.specialization')),
                ('time_slots', models.ManyToManyField(related_name='trainers', to='app.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='userrating',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trainer'),
        ),
    ]
