# Generated by Django 4.2.5 on 2023-11-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_trainer_userrating_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='time_slots',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
