# Generated by Django 4.2.5 on 2024-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_transformation_recipe_fitnessupdate_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fitness_updates/'),
        ),
    ]
