# Generated by Django 4.2.5 on 2024-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_discussion_title_alter_fitnessupdate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transformations/'),
        ),
    ]
