# Generated by Django 4.2.5 on 2024-02-27 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_cartitem_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='discussion_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
