# Generated by Django 4.2.5 on 2024-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
