# Generated by Django 4.2.5 on 2024-02-28 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_discussion_likes_comment_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='likes',
            field=models.ManyToManyField(related_name='liked_discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
