# Generated by Django 4.2.5 on 2024-02-28 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_discussion_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='likes',
            field=models.ManyToManyField(related_name='liked_transformations', to=settings.AUTH_USER_MODEL),
        ),
    ]
