# Generated by Django 4.2.5 on 2024-02-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_transformation_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='transformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.transformation'),
        ),
    ]
