# Generated by Django 4.2.5 on 2024-02-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
