# Generated by Django 4.2.5 on 2024-03-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_rentalrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalRating',
            new_name='Productrating',
        ),
    ]
