# Generated by Django 4.2.5 on 2024-03-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_rename_rentalrating_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.productrating'),
        ),
    ]
