# Generated by Django 4.2.5 on 2024-03-01 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_product1_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_rated', to='app.product1'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='rated_products', to='app.productrating'),
        ),
    ]
