# Generated by Django 4.2.5 on 2024-03-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_productrating_product_alter_product1_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile1',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
