# Generated by Django 4.2.5 on 2024-03-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_managers'),
        ('app', '0002_userprofile'),
        ('app', '0057_userprofile1_address_userprofile1_pincode'),
    ]

    operations = [
    ]
