# Generated by Django 4.2.5 on 2024-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_booking_delete_payment_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_acceped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        # migrations.DeleteModel(
        #     name='userprofile',
        # ),
    ]
