# Generated by Django 4.2.5 on 2024-03-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_payment_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('workout_details', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='workout_videos/')),
                ('additional_notes', models.TextField(blank=True)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='userprofile',
        # ),
    ]
