# Generated by Django 4.2.5 on 2024-04-04 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_workoutschedule_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date_time', models.DateTimeField()),
                ('workout_details', models.TextField()),
                ('meet_link', models.URLField()),
                ('additional_notes', models.TextField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='userprofile',
        #     name='user',
        # ),
        # migrations.DeleteModel(
        #     name='WorkoutSchedule',
        # ),
        # migrations.DeleteModel(
        #     name='userprofile',
        # ),
    ]
