# Generated by Django 4.2.5 on 2024-04-04 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_workoutclass_remove_userprofile_user_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='userprofile',
        #     name='user',
        # ),
        migrations.DeleteModel(
            name='WorkoutSchedule',
        ),
        migrations.AddField(
            model_name='trainer',
            name='user',
            field=models.ForeignKey(default=64, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # migrations.DeleteModel(
        #     name='userprofile',
        # ),
    ]
