# Generated by Django 4.2.5 on 2024-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_remove_userprofile_user_delete_workoutschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('week1', 'Week 1'), ('week2', 'Week 2'), ('week3', 'Week 3'), ('week4', 'Week 4'), ('week5', 'Week 5'), ('week6', 'Week 6'), ('week7', 'Week 7'), ('week8', 'Week 8'), ('week9', 'Week 9'), ('week10', 'Week 10'), ('week11', 'Week 11'), ('week12', 'Week 12')], max_length=10)),
                ('workout_text', models.TextField()),
            ],
        ),
        # migrations.DeleteModel(
        #     name='userprofile',
        # ),
    ]
