# Generated by Django 4.2.5 on 2024-04-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_workout_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_text',
            new_name='workout_details',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(default='', max_length=100),
        ),
        # migrations.DeleteModel(
        #     name='userprofile',
        # ),
    ]
