# Generated by Django 4.2.5 on 2024-04-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_rename_workout_text_workout_workout_details_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='userprofile',
        # ),
    ]
