# Generated by Django 4.2.5 on 2024-04-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutclass',
            name='workout_details',
        ),
        migrations.AddField(
            model_name='workoutclass',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.workout'),
        ),
        # migrations.DeleteModel(
        #     name='userprofile',
        # ),
    ]
