# Generated by Django 4.2.5 on 2024-04-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_remove_workoutclass_workout_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutclass',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='workoutclass',
            name='user',
        ),
        #migrations.DeleteModel(
            #name='userprofile',
        #),
        migrations.DeleteModel(
            name='WorkoutClass',
        ),
    ]
