# Generated by Django 4.2.5 on 2024-04-08 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_remove_workoutclass_trainer_remove_workoutclass_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date_time', models.DateTimeField()),
                ('meet_link', models.URLField()),
                ('additional_notes', models.TextField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workout')),
            ],
        ),
        #migrations.DeleteModel(
          #  name='userprofile',
        #),
    ]
