# Generated by Django 4.2.5 on 2024-04-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_workoutclass_delete_userprofile'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='userprofile',
        # ),
    ]
